### PR TITLE
👷 Actions: Add Docker build and push

### PR DESCRIPTION
**Pull request by ThePooN**
Builds a Docker image and push to Docker Hub every time a tag is pushed.

### CODE REVIEW

**Comment by peppy** [comment]
Just for reference, was this publish script taken from another project where it's already working?

**Comment by ThePooN** [comment]
Yeah, got it from [here](https://github.com/docker/build-push-action).

If you open the actions on my forks, you'll see it works (except last commit as I replaced the repo name by yours).

Forgot to specify you need to set the DOCKER_USERNAME and DOCKER_PASSWORD (which can be an access token), of course

**Comment by peppy** [comment]
Hmm, just looking at other usages we have where we are publishing and this came up: https://github.com/ppy/osu-notification-server/blob/master/.github/workflows/pack.yml

Probably worth either copying that for consistency, or if there's reason, applying the version you have here to all existing deployments.

**Comment by ThePooN** [comment]
Yeah, that's the first thing I looked into, then realized it wasn't up-to-date. I'll PR this to the other repos then.

**Review by peppy — APPROVED** [review]

**Pull request merged**
